name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 9.0.6
      - uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4
      - run: git branch --track main origin/main
        if: ${{ github.event_name == 'pull_request' }}
      # - run: pnpm exec nx-cloud record -- nx format:check
      - run: pnpm exec nx affected -t lint test build
